stages:
- test
- integration_test

all_branch_test:
  stage: test
  tags:
  - vtb-test-docker
  image: python:3.6
  script:
  - pip install -r requirements-dev.txt --no-cache-dir
  - pytest --cov=cabbage tests/

integration_test:
  stage: integration_test
  tags:
  - vtb-test-docker
  image: python:3.6
  services:
  - rabbitmq:3.7-management-alpine
  script:
  - pip install -r requirements-dev.txt --no-cache-dir
  - pytest tests_integration/
