variables:
  REGISTRY_URL: $CI_REGISTRY/public_repos/images/

stages:
- test
- integration_test

all_branch_test:
  stage: test
  tags:
  - build-docker
  image: ${REGISTRY_URL}python:3.6
  script:
  - pip install -r requirements-dev.txt --no-cache-dir
  - pytest --cov=cabbage tests/

integration_test:
  stage: integration_test
  tags:
  - build-docker
  image: ${REGISTRY_URL}python:3.6
  variables:
    TEST_RABBITMQ_HOST: rabbitmq
  services:
  - name: ${REGISTRY_URL}rabbitmq:management-alpine
    alias: rabbitmq
  script:
  - pip install -r requirements-dev.txt --no-cache-dir
  - pytest tests_integration/
